---
- name: Backup Device Config
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather Ansible facts
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Date/Time Timestamp variables
      set_fact:
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      delegate_to: localhost
      run_once: yes

    - name: Download Device Config
      community.network.edgeos_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}-{{ yyyymmddhhmm }}.txt"
